### ISSUE TITLE
请问怎么查看实验结果？怎么才能得到论文里图7-9描述的结论？

### ISSUE THREAD

**Issue by flyzerr** [SamuelGong/Pisces#1]
您好！

我在执行 Readme 中 Running Experiments 部分遇到了一点问题，想向您请教一下。

在执行完 bash run.sh start_a_task fig7to9/mnist-pisces.yml 命令后，终端输出和 Readme 中描述的一样，但是我不知道运行结果存放到什么地方了。只是多了一个以时间戳命名的文件夹，文件夹里有一个 config.yml 文件，我不清楚 config.yml 这个文件应该怎么用，或者说这个文件描述了什么，不太懂怎样才能得到论文中图7-9描述的结论。

希望作者或者其他有了解的朋友可以帮忙解答一下！非常感谢！

**Comment by SamuelGong** [comment]
Seems that the task is not launched successfully. Could you please find the file `last_response.json` and tell me what it tells? It should be within the same folder as where `run.sh` resides.

**Comment by flyzerr** [comment]
> Seems that the task is not launched successfully. Could you please find the file `last_response.json` and tell me what it tells? It should be within the same folder as where `run.sh` resides.

last_response.json 文件内容太多了，我把里面的内容复制到这个链接里了，您可以看一下：https://paste.ubuntu.com/p/3zXNZQ9VnH/

为了节约成本，我没有设置那么多clients，只设置了3个，并且他们的类型也不是c5.4xlarge，而是t2.micro，不知道这样会不会影响实验结果？

**Comment by SamuelGong** [comment]
What I saw in the log:

* For the first node (i.e., `worker-1`) that you reserved for Client 1 to Client 67:
  * **Line 7** indicates that the script (running at your local host) connected to your `worker-1` machine and ran the following commands successfully:
  ```bash
  mkdir -p Pisces/experiments/socc22_ae/fig7to9 && cd Pisces/experiments/socc22_ae/fig7to9 && mkdir -p 20230218-145231
  ```
  This essentially created a folder `/home/ubuntu/Pisces/experiments/socc22_ae/fig7to9` at `worker-1`. Please first check if this is true by double-checking the actual file system.
  * **Line 13** indicates that the script then ran the following commands successfully at your local host:
  ```bash
  scp -q -i /mnt/c/Users/flyzer/Desktop/Pisces/experiments/socc22_ae/../dev/MyKeyPair.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null /mnt/c/Users/flyzer/Desktop/Pisces/experiments/socc22_ae/fig7to9/20230218-145231/config.yml ubuntu@52.32.80.58:~/Pisces/experiments/socc22_ae/fig7to9/20230218-145231/pisces-worker-1-config.yml
  ```
  This basically copied the file `config.yml` from your local host (located at `/mnt/c/Users/flyzer/Desktop/Pisces/experiments/socc22_ae/fig7to9/20230218-145231`, i.e., the only file that you saw) to `worker-1` (located at `~/Pisces/experiments/socc22_ae/fig7to9/20230218-145231`). Please also check this out manually.

  * **Line 18** indicates that the script then ran the following commands at `worker-1`:
  ```bash
  cat ~/Pisces/experiments/socc22_ae/fig7to9/20230218-145231/pisces-worker-1-config.yml > ~/Pisces/experiments/socc22_ae/fig7to9/20230218-145231/log.txt
  ```
  **but failed with errors**
  ```
  cat: /home/ubuntu/Pisces/experiments/socc22_ae/fig7to9/20230218-145231/pisces-worker-1-config.yml: No such file or directory
  ```
  which contradicts with the observation I made in Line 13. So if `pisces-worker-1-config.yml` does not exist in the respective location. Then I suspected that what Line 13 indicates is wrong--the copying was not successful at all. If that is the case, you can try run the following command at your local host (i.e., via a terminal) to see if you can manually copy the file:

  ```
  scp -q -i /mnt/c/Users/flyzer/Desktop/Pisces/experiments/socc22_ae/../dev/MyKeyPair.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null /mnt/c/Users/flyzer/Desktop/Pisces/experiments/socc22_ae/fig7to9/20230218-145231/config.yml ubuntu@52.32.80.58:~/Pisces/experiments/socc22_ae/fig7to9/20230218-145231/pisces-worker-1-config.yml
  ```
  If you can not even do this manually, then please check you can do `scp` to transmit a file from your local host to `worker-1`. If still not, please check the firewall of `worker-1` to see if port `22` is accessible for your local host.

* (omitted until we solved the above problem)

**Comment by flyzerr** [comment]
您好！

感谢您的耐心解答，上次的问题已经解决了。主要是因为 MyKeyPair.pem 权限的问题，使用 chmod 600 MyKeyPair.pem 修改密钥权限就可以了。

然后我执行 bash run.sh start_a_task fig7to9/mnist-pisces.yml 命令，得到了result.csv 文件，里面显示了模型的准确率和训练时间。

不过现在我还是有点问题，就是训练好的模型保存到哪里了呢？我去其中一个worker中看log，上面写的是把模型存到了 ./models/pretrained/lenet5_4_6542.pth 路径下：
> [INFO][(02-28) 10:32:39] [basic.py:94]: [Client #4] Model saved to ./models/pretrained/lenet5_4_6542.pth.

但是根本没有这个路径。想问一下怎么获取训练好的模型呢？
这是 pisces-worker-1 的log：https://paste.ubuntu.com/p/GJHrMY2GTh/

**Comment by SamuelGong** [comment]
> 您好！
> 
> 感谢您的耐心解答，上次的问题已经解决了。主要是因为 MyKeyPair.pem 权限的问题，使用 chmod 600 MyKeyPair.pem 修改密钥权限就可以了。
> 
> 然后我执行 bash run.sh start_a_task fig7to9/mnist-pisces.yml 命令，得到了result.csv 文件，里面显示了模型的准确率和训练时间。
> 
> 不过现在我还是有点问题，就是训练好的模型保存到哪里了呢？我去其中一个worker中看log，上面写的是把模型存到了 ./models/pretrained/lenet5_4_6542.pth 路径下：
> 
> > [INFO][(02-28) 10:32:39] [basic.py:94]: [Client #4] Model saved to ./models/pretrained/lenet5_4_6542.pth.
> 
> 但是根本没有这个路径。想问一下怎么获取训练好的模型呢？ 这是 pisces-worker-1 的log：https://paste.ubuntu.com/p/GJHrMY2GTh/

Glad to hear that you can have it run.

Suppose that the resulting folder for the task is `fig7to9/[some timestamp]`, have you checked the folder `fig7to9/[some timestamp]/models/pretrained/lenet5_4_6542.pth`?

**Comment by flyzerr** [comment]
您好!

pisces-coordinator 实例的 fig7to9/[some timestamp] 目录下只有log.txt, pisces-coordinator-config.yml, result.csv 这三个文件.

pisces-worker-1 实例的 fig7to9/[some timestamp] 目录下只有log.txt, pisces-worker-1-config.yml 这两个文件.

log 里显示模型保存到了 ./models/pretrained/lenet5_4_6542.pth , 但是 fig7to9/[some timestamp] 目录下并没有 models 这个文件夹.

是哪里出问题了么?

**Comment by SamuelGong** [comment]
This reminds me that I have disabled model stores for clients out of space considerations.

https://github.com/SamuelGong/Pisces/blob/61fff7d57766000828db30d88ce28f3dd43bc97d/plato/trainers/base.py#L118

Please comment this block of code to see if each client's model can then be found.

**Comment by flyzerr** [comment]
您好!

我在pisces-coordinator 实例和 pisces-worker-1 实例中  `Pisces/models/pretrained` 目录下找到了pth文件, 而不是在 `Pisces/experiments/socc22_ae/fig7to9/[sometimestamp]/models/pretrained` 目录下 (`Pisces/experiments/socc22_ae/fig7to9/[some timestamp]`目录下根本就没有 `models` 这个文件夹) , 是哪出了问题么?

还有个问题我想确认一下:
我理解的是: README.md 中 **Install and Configure AWS CLI** 部分应该在我本地和 pisces-coordinator 实例中都执行一遍, README.md 中的其他部分应该全是在我本地执行. 想问一下您, 我理解的对么?

**Comment by SamuelGong** [comment]
I have fixed the path issue by upgrading the code. Please pull and try it out. You should be able to find the `models` folder now at `Pisces/experiments/socc22_ae/fig7to9/[sometimestamp]` for both the server and clients (provided that you have commented the code snippets as mentioned above).

By the way, in the original README, "coordinator node" should be referring to your host machine, instead of the server or a client in the FL cluster. Sorry for the confusion and the ambiguity in the text should be fixed now. Please also see if that makes sense to you.

**Comment by flyzerr** [comment]
您好!
我更新完代码之后, 然后把删除`model_file`的那条语句注释掉之后, 在 `Pisces/experiments/socc22_ae/fig7to9/[sometimestamp]/models/pretrained/` 路径下找到了 pth 文件.
非常感谢您的耐心指点, 有问题再向您请教.

**Comment by SamuelGong** [comment]
Glad to help you out! Please do not hesitate to open new issues if you encounter any new problems.

Please also consider citing our paper if you use the code or data in your research project! Thank you.
